theme: jekyll-theme-minima
name: Jianan Lin (林家南)
title: Jianan Lin - Software Engineer & TCS Researcher
description: Mid-level Software Engineer & Theoretical Computer Science Independent Researcher | FDU & RPI Graduate
